
listen = "0.0.0.0:1000"

[database]
host = "127.0.0.1"
Port = 3306
username = "testuser"
dbname = "testdb"

[auth]
auth_type = "http"

[auth.http_auth]
endpoint = "http://127.0.0.1:2000"
request_header = { a = "b" }
